apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: # TODO
        ports:
        - containerPort: 8002
        env:
          - name: SERVICE_C_URL
            value: service-c-svc


