apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: # TODO
        ports:
        - containerPort: 8003
        env:
          - name: DB_HOST
            value: "mysql-svc"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "weather"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: 'password'